
number = 16
title = "2024-02"
publish = true


[[article]]
file = "voice.md"
path = "/433"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/434"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-02"
publish = true
featured = true
