
number = 16
title = "2024-02"
publish = true


[[article]]
file = "voice.md"
path = "/433"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/434"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/435"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/436"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/437"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/438"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/439"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/440"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/441"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/442"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/443"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-11"
publish = true
featured = false
