
number = 16
title = "2024-02"
publish = true


[[article]]
file = "voice.md"
path = "/433"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/434"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/435"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/436"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/437"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/438"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/439"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/440"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/441"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/442"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/443"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/444"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/445"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/446"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/447"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/448"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/449"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/450"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/451"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/452"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/453"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/454"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/455"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/456"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/457"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/458"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-26"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/459"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-02-27"
publish = true
featured = false
