
number = 10
title = "2023-08"
publish = true


[[article]]
file = "voice.md"
path = "/249"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/250"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/251"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/252"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/253"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-05"
publish = true
featured = true
