
number = 10
title = "2023-08"
publish = true


[[article]]
file = "voice.md"
path = "/249"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/250"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/251"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/252"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/253"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/254"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/255"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/256"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/257"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/258"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/259"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/260"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/261"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/262"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/263"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/264"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/265"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/266"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-08-18"
publish = true
featured = false
