
number = 27
title = "2025-01"
publish = true


[[article]]
file = "voice.md"
path = "/768"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/769"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/770"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/771"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/772"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/773"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/774"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-07"
publish = true
featured = false
