
number = 27
title = "2025-01"
publish = true


[[article]]
file = "voice.md"
path = "/768"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/769"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/770"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/771"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/772"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/773"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/774"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/775"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/776"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/777"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/778"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/779"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/780"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/781"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/782"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/783"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/784"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/785"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/786"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/787"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/788"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/789"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/790"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/791"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/792"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-01-25"
publish = true
featured = false
