
number = 26
title = "2024-12"
publish = true


[[article]]
file = "voice.md"
path = "/737"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/738"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/739"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/740"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/741"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/742"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/743"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/744"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/745"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/746"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/747"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/748"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/749"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/750"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/751"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/752"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/753"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/754"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/755"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/756"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/757"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/758"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/759"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/760"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-24"
publish = true
featured = false
