
number = 26
title = "2024-12"
publish = true


[[article]]
file = "voice.md"
path = "/737"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/738"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/739"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/740"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/741"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/742"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/743"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/744"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/745"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/746"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/747"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/748"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-12"
publish = true
featured = false
