
number = 26
title = "2024-12"
publish = true


[[article]]
file = "voice.md"
path = "/737"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/738"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/739"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-12-03"
publish = true
featured = true
