
number = 30
title = "2025-04"
publish = true


[[article]]
file = "voice.md"
path = "/858"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/859"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/860"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/861"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/862"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/863"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/864"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/865"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/866"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/867"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/868"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/869"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/870"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/871"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/872"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/873"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/874"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/875"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/876"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-04-19"
publish = true
featured = false
