
number = 7
title = "2023-05"
publish = true


[[article]]
file = "voice.md"
path = "/157"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/158"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/159"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/160"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/161"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/162"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/163"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-05-07"
publish = true
featured = false
