
number = 33
title = "2025-07"
publish = true


[[article]]
file = "voice.md"
path = "/949"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/950"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/951"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/952"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-04"
publish = true
featured = true
