
number = 33
title = "2025-07"
publish = true


[[article]]
file = "voice.md"
path = "/949"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/950"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/951"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/952"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/953"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/954"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/955"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/956"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/957"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/958"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/959"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/960"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/961"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/962"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/963"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/964"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/965"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/966"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/967"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-07-19"
publish = true
featured = false
