
number = 28
title = "2025-02"
publish = true


[[article]]
file = "voice.md"
path = "/799"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/800"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/801"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/802"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/803"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/804"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/805"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/806"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/807"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/808"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/809"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/810"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/811"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/812"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/813"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/814"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/815"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/816"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/817"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-19"
publish = true
featured = false
