
number = 28
title = "2025-02"
publish = true


[[article]]
file = "voice.md"
path = "/799"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/800"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/801"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/802"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/803"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/804"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/805"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-02-07"
publish = true
featured = false
