
number = 2
title = "2022-12"

[[article]]
file = "voice.md"
path = "/6"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/7"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-02"
publish = true
featured = true
