
number = 2
title = "2022-12"

[[article]]
file = "voice.md"
path = "/6"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/7"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/8"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/9"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/10"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/11"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/12"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/13"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/14"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/15"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/16"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/17"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/18"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/19"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/20"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/21"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/22"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/23"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/24"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/25"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/26"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/27"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/28"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/29"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/30"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/31"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-26"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/32"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-27"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/33"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-28"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/34"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-29"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/35"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-30"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/36"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-31"
publish = true
featured = false
