
number = 2
title = "2022-12"

[[article]]
file = "voice.md"
path = "/6"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/7"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/8"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/9"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/10"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/11"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/12"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/13"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/14"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/15"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/16"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2022-12-11"
publish = true
featured = false
