
number = 34
title = "2025-08"
publish = true


[[article]]
file = "voice.md"
path = "/980"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/981"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/982"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/983"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/984"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/985"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/986"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/987"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/988"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/989"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/990"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/991"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/992"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/993"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/994"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/995"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/996"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/997"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/998"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/999"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1000"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1001"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-08-22"
publish = true
featured = false
