
number = 32
title = "2025-06"
publish = true


[[article]]
file = "voice.md"
path = "/919"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/920"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/921"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/922"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/923"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/924"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/925"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/926"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/927"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/928"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/929"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/930"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/931"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/932"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/933"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/934"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/935"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/936"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/937"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/938"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/939"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/940"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/941"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-06-23"
publish = true
featured = false
