
number = 12
title = "2023-10"
publish = true


[[article]]
file = "voice.md"
path = "/310"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/311"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/312"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/313"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/314"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/315"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/316"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/317"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-08"
publish = true
featured = false
