
number = 12
title = "2023-10"
publish = true


[[article]]
file = "voice.md"
path = "/310"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/311"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/312"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/313"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/314"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/315"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/316"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/317"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/318"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/319"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/320"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/321"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/322"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/323"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/324"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/325"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/326"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/327"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/328"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/329"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/330"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/331"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/332"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-23"
publish = true
featured = false
