
number = 12
title = "2023-10"
publish = true


[[article]]
file = "voice.md"
path = "/310"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/311"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-10-02"
publish = true
featured = true
