
number = 21
title = "2024-07"
publish = true


[[article]]
file = "voice.md"
path = "/584"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/585"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/586"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/587"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-04"
publish = true
featured = true
