
number = 21
title = "2024-07"
publish = true


[[article]]
file = "voice.md"
path = "/584"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/585"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/586"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/587"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/588"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/589"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/590"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/591"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/592"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/593"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/594"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/595"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/596"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/597"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/598"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/599"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/600"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/601"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-07-18"
publish = true
featured = false
