
number = 48
title = "2026-10"
publish = true


[[article]]
file = "voice.md"
path = "/1403"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1404"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1405"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1406"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1407"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1408"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1409"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-10-07"
publish = true
featured = false
