
number = 6
title = "2023-04"
publish = true


[[article]]
file = "voice.md"
path = "/127"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/128"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/129"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/130"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/131"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/132"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/133"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/134"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/135"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/136"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/137"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/138"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-04-12"
publish = true
featured = false
