
number = 20
title = "2024-06"
publish = true


[[article]]
file = "voice.md"
path = "/554"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/555"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/556"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/557"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/558"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/559"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/560"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/561"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/562"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-09"
publish = true
featured = false
