
number = 20
title = "2024-06"
publish = true


[[article]]
file = "voice.md"
path = "/554"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/555"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/556"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/557"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/558"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/559"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/560"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/561"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/562"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/563"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/564"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/565"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/566"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/567"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/568"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/569"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/570"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/571"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/572"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/573"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/574"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/575"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-06-22"
publish = true
featured = false
