
number = 24
title = "2024-10"
publish = true


[[article]]
file = "voice.md"
path = "/676"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/677"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/678"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/679"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-04"
publish = true
featured = true
