
number = 24
title = "2024-10"
publish = true


[[article]]
file = "voice.md"
path = "/676"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/677"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/678"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/679"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/680"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/681"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/682"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/683"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/684"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/685"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/686"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-11"
publish = true
featured = false
