
number = 24
title = "2024-10"
publish = true


[[article]]
file = "voice.md"
path = "/676"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/677"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/678"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/679"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/680"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/681"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/682"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/683"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/684"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/685"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/686"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/687"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/688"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/689"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/690"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/691"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/692"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/693"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/694"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/695"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/696"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/697"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/698"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/699"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/700"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/701"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-26"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/702"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-27"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/703"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-28"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/704"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-10-29"
publish = true
featured = false
