
number = 13
title = "2023-11"
publish = true


[[article]]
file = "voice.md"
path = "/341"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/342"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/343"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/344"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/345"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/346"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/347"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/348"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/349"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/350"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/351"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/352"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/353"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/354"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/355"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/356"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/357"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/358"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/359"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/360"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/361"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/362"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/363"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/364"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-11-24"
publish = true
featured = false
