
number = 19
title = "2024-05"
publish = true


[[article]]
file = "voice.md"
path = "/523"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/524"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/525"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/526"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/527"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/528"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/529"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-07"
publish = true
featured = false
