
number = 19
title = "2024-05"
publish = true


[[article]]
file = "voice.md"
path = "/523"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/524"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/525"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/526"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/527"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/528"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/529"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/530"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/531"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/532"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/533"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/534"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/535"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/536"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/537"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/538"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/539"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/540"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/541"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/542"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-20"
publish = true
featured = false
