
number = 19
title = "2024-05"
publish = true


[[article]]
file = "voice.md"
path = "/523"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/524"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-05-02"
publish = true
featured = true
