
number = 9
title = "2023-07"
publish = true


[[article]]
file = "voice.md"
path = "/218"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/219"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/220"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/221"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/222"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/223"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/224"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/225"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/226"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/227"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/228"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/229"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/230"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/231"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/232"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/233"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/234"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/235"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/236"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/237"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/238"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/239"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-22"
publish = true
featured = false
