
number = 9
title = "2023-07"
publish = true


[[article]]
file = "voice.md"
path = "/218"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/219"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/220"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/221"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/222"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/223"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/224"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/225"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/226"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/227"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/228"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/229"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-12"
publish = true
featured = false
