
number = 9
title = "2023-07"
publish = true


[[article]]
file = "voice.md"
path = "/218"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/219"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/220"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/221"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-07-04"
publish = true
featured = true
