
number = 42
title = "2026-04"
publish = true


[[article]]
file = "voice.md"
path = "/1223"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1224"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1225"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1226"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1227"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1228"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1229"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1230"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1231"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1232"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1233"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1234"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1235"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1236"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1237"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1238"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1239"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1240"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1241"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-19"
publish = true
featured = false
