
number = 42
title = "2026-04"
publish = true


[[article]]
file = "voice.md"
path = "/1223"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1224"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1225"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1226"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1227"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-04-05"
publish = true
featured = true
