
number = 15
title = "2024-01"
publish = true


[[article]]
file = "voice.md"
path = "/402"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/403"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/404"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/405"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/406"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/407"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/408"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/409"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/410"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/411"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/412"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/413"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/414"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/415"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/416"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/417"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/418"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/419"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-01-18"
publish = true
featured = false
