
number = 23
title = "2024-09"
publish = true


[[article]]
file = "voice.md"
path = "/646"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/647"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/648"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/649"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/650"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/651"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/652"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/653"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/654"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/655"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/656"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/657"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/658"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/659"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/660"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/661"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/662"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/663"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/664"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/665"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/666"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/667"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-22"
publish = true
featured = false
