
number = 23
title = "2024-09"
publish = true


[[article]]
file = "voice.md"
path = "/646"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/647"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-02"
publish = true
featured = true
