
number = 23
title = "2024-09"
publish = true


[[article]]
file = "voice.md"
path = "/646"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/647"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/648"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/649"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/650"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/651"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/652"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/653"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/654"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/655"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-09-10"
publish = true
featured = false
