
number = 3
title = "2023-01"


[[article]]
file = "voice.md"
path = "/37"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/38"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/39"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/40"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/41"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/42"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/43"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/44"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/45"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/46"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/47"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/48"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/49"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/50"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/51"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/52"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-16"
publish = true
featured = false
