
number = 3
title = "2023-01"


[[article]]
file = "voice.md"
path = "/37"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/38"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-02"
publish = true
featured = true
