
number = 3
title = "2023-01"


[[article]]
file = "voice.md"
path = "/37"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/38"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/39"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/40"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/41"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/42"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/43"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/44"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/45"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/46"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/47"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/48"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/49"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/50"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/51"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/52"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/53"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/54"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/55"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/56"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/57"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/58"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/59"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/60"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/61"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/62"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-01-26"
publish = true
featured = false
