
number = 22
title = "2024-08"
publish = true


[[article]]
file = "voice.md"
path = "/615"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/616"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-02"
publish = true
featured = true
