
number = 22
title = "2024-08"
publish = true


[[article]]
file = "voice.md"
path = "/615"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/616"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/617"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/618"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/619"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/620"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/621"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/622"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/623"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/624"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/625"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/626"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/627"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/628"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/629"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/630"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/631"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/632"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/633"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/634"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/635"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/636"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/637"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/638"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/639"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/640"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-26"
publish = true
featured = false
