
number = 22
title = "2024-08"
publish = true


[[article]]
file = "voice.md"
path = "/615"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/616"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/617"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/618"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/619"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/620"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/621"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/622"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/623"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-08-09"
publish = true
featured = false
