
number = 4
title = "2023-02"


[[article]]
file = "voice.md"
path = "/68"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/69"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/70"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-03"
publish = true
featured = true
