
number = 4
title = "2023-02"


[[article]]
file = "voice.md"
path = "/68"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/69"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/70"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/71"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/72"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/73"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/74"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-07"
publish = true
featured = false
