
number = 4
title = "2023-02"


[[article]]
file = "voice.md"
path = "/68"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/69"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/70"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/71"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/72"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/73"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/74"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/75"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/76"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/77"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/78"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/79"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/80"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/81"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/82"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/83"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/84"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/85"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-02-18"
publish = true
featured = false
