
number = 45
title = "2026-07"
publish = true


[[article]]
file = "voice.md"
path = "/1313"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1314"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1315"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1316"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1317"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1318"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1319"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1320"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1321"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1322"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1323"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1324"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-07-12"
publish = true
featured = false
