
number = 47
title = "2026-09"
publish = true


[[article]]
file = "voice.md"
path = "/1373"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1374"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1375"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1376"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1377"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1378"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1379"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1380"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1381"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1382"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1383"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1384"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1385"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1386"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1387"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2026-09-15"
publish = true
featured = false
