
number = 36
title = "2025-10"
publish = true


[[article]]
file = "voice.md"
path = "/1041"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1042"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1043"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1044"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1045"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1046"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1047"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1048"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1049"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1050"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1051"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1052"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1053"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1054"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1055"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1056"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1057"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1058"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1059"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1060"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1061"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1062"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1063"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1064"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-24"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1065"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-25"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1066"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-26"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1067"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-27"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1068"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-28"
publish = true
featured = false
