
number = 36
title = "2025-10"
publish = true


[[article]]
file = "voice.md"
path = "/1041"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1042"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1043"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1044"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1045"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1046"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1047"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-07"
publish = true
featured = false
