
number = 36
title = "2025-10"
publish = true


[[article]]
file = "voice.md"
path = "/1041"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1042"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-10-02"
publish = true
featured = true
