
number = 14
title = "2023-12"
publish = true


[[article]]
file = "voice.md"
path = "/371"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/372"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/373"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/374"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/375"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/376"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/377"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/378"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/379"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/380"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/381"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/382"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/383"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/384"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/385"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/386"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/387"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-17"
publish = true
featured = false
