
number = 14
title = "2023-12"
publish = true


[[article]]
file = "voice.md"
path = "/371"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/372"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/373"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/374"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-12-04"
publish = true
featured = true
