
number = 18
title = "2024-04"
publish = true


[[article]]
file = "voice.md"
path = "/493"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/494"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/495"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/496"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/497"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/498"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/499"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/500"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/501"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/502"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/503"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/504"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/505"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/506"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/507"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-04-15"
publish = true
featured = false
