
number = 35
title = "2025-09"
publish = true


[[article]]
file = "voice.md"
path = "/1011"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1012"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1013"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1014"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-04"
publish = true
featured = true
