
number = 35
title = "2025-09"
publish = true


[[article]]
file = "voice.md"
path = "/1011"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1012"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1013"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1014"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1015"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1016"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1017"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1018"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-08"
publish = true
featured = false
