
number = 35
title = "2025-09"
publish = true


[[article]]
file = "voice.md"
path = "/1011"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1012"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1013"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1014"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1015"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/1016"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1017"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1018"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1019"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1020"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1021"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1022"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1023"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1024"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1025"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1026"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/1027"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2025-09-17"
publish = true
featured = false
