
number = 11
title = "2023-09"
publish = true


[[article]]
file = "voice.md"
path = "/280"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/281"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/282"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-03"
publish = true
featured = true
