
number = 11
title = "2023-09"
publish = true


[[article]]
file = "voice.md"
path = "/280"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/281"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/282"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/283"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/284"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/285"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/286"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/287"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/288"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/289"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/290"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/291"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/292"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/293"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/294"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/295"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/296"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/297"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/298"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/299"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/300"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/301"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-09-22"
publish = true
featured = false
