
number = 8
title = "2023-06"
publish = true


[[article]]
file = "voice.md"
path = "/188"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/189"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/190"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/191"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/192"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/193"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/194"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/195"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/196"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-09"
publish = true
featured = false
