
number = 8
title = "2023-06"
publish = true


[[article]]
file = "voice.md"
path = "/188"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/189"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/190"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/191"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/192"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/193"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/194"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/195"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/196"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/197"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/198"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/199"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/200"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/201"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/202"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-15"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/203"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-16"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/204"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-17"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/205"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-18"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/206"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-19"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/207"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-20"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/208"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-21"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/209"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-22"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/210"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-23"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/211"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-24"
publish = true
featured = false
