
number = 8
title = "2023-06"
publish = true


[[article]]
file = "voice.md"
path = "/188"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/189"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2023-06-02"
publish = true
featured = true
