
number = 25
title = "2024-11"
publish = true


[[article]]
file = "voice.md"
path = "/707"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/708"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/709"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/710"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-04"
publish = true
featured = true
