
number = 25
title = "2024-11"
publish = true


[[article]]
file = "voice.md"
path = "/707"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-01"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/708"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-02"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/709"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-03"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/710"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-04"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/711"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-05"
publish = true
featured = true

[[article]]
file = "voice.md"
path = "/712"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-06"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/713"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-07"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/714"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-08"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/715"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-09"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/716"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-10"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/717"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-11"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/718"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-12"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/719"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-13"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/720"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-14"
publish = true
featured = false

[[article]]
file = "voice.md"
path = "/721"
title = "◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️"
author = "paranoic"
pub_date = "2024-11-15"
publish = true
featured = false
